# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPutUpAndIn <- function(nInt = 100L, S0 = 105, StrikeK = 100, VolR = 0.22, Rfr = 0.05, Time = 0.5, nReps = 100L) {
    .Call(`_cppPackage_getPutUpAndIn`, nInt, S0, StrikeK, VolR, Rfr, Time, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_cppPackage_rcpp_hello_world`)
}

